name: Patch and Build

on:
  workflow_dispatch:

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches
      - name: Build
        run: ./gradlew build
      - name: Create Folia Jar
        run: ./gradlew createMojmapPaperclipJar --stacktrace --info
      - name: Zip API & Jar
        run: zip -r /home/runner/work/Folia-Actions/Folia-Actions.zip /home/runner/work/Folia-Actions/Folia-Actions/Folia-Server/build/libs/ /home/runner/work/Folia-Actions/Folia-Actions/Folia-API/build/libs/
      - name: Upload Folia Jar
        uses: actions/upload-artifact@v4
        with:
          name: folia.zip
          path: /home/runner/work/Folia-Actions/Folia-Actions.zip
          retention_days: 1
